# Generated by Django 3.0.3 on 2020-07-11 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20200711_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutionfile',
            name='auther',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Developer'),
        ),
        migrations.AddField(
            model_name='solutionfile',
            name='problem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Challenge'),
        ),
    ]
